// RELIABILITY: the archive commit-back must persist every generated artifact
// the site serves.
//
// publish.yml deploys `site/` first and then commits a snapshot of the
// generated artifacts back to main. Any render output missing from that
// `git add` list silently forks the repo from the deploy: Pages serves a fresh
// copy while the branch keeps an old one. That already happened once for
// dashboard/accuracy/accuracy.json (CLAUDE.md issue 011) and again for the
// canonical schedule, its audit, and the season calendar, which sat at their
// 2026-06-28 state on main while the deploy was regenerated daily. The
// canonical schedule is documented as the repo-owned source of truth, so the
// checkout and the deploy must not disagree.

import { readFileSync } from "node:fs";
import { test, run, assert } from "./_harness.mjs";

const workflow = readFileSync(new URL("../../.github/workflows/publish.yml", import.meta.url), "utf8");

function persistBlock() {
  const start = workflow.indexOf("- name: Persist archive snapshot");
  assert.ok(start >= 0, "sanity: located the Persist archive snapshot step");
  const gitAdd = workflow.indexOf("git add -A", start);
  assert.ok(gitAdd >= 0, "sanity: located the git add list");
  const end = workflow.indexOf("git diff --cached", gitAdd);
  assert.ok(end > gitAdd, "sanity: located the end of the git add list");
  return workflow.slice(gitAdd, end);
}

// Generated by render.mjs (or by a stage it orchestrates) and served from the
// same path in site/, so the branch copy must track the deployed copy.
const REQUIRED_PERSISTED_PATHS = [
  "index.html",
  "archive.json",
  "archive",
  "issues",
  "status.json",
  "latest.json",
  "delivery-status.json",
  "dashboard/accuracy/accuracy.json",
  "data/phillies-2026.json",
  "data/phillies-2026-audit.json",
  "data/phillies-2026-overrides.json",
  "calendar/phillies-2026-all.ics",
  "robots.txt",
  "sitemap.xml",
  "feed.xml",
  "manifest.webmanifest",
  "favicon.svg",
  "og-default.svg",
];

test("PIN: persist step commits every generated artifact the site serves", () => {
  const block = persistBlock();
  const tokens = new Set(
    block
      .replace(/\\\n/g, " ")
      .split(/\s+/)
      .filter(Boolean),
  );
  for (const path of REQUIRED_PERSISTED_PATHS) {
    assert.ok(tokens.has(path), `persist step must git add ${path}`);
  }
});

test("PIN: canonical schedule artifacts are persisted with the rest of the render output", () => {
  const block = persistBlock();
  assert.match(block, /data\/phillies-2026\.json/);
  assert.match(block, /data\/phillies-2026-audit\.json/);
  assert.match(block, /calendar\/phillies-2026-all\.ics/);
});

await run();
